--users
INSERT INTO users (username, password) VALUES ('testuser', '$2y$10$rkgcyVHBFcVhaYbCqN6f1OuWTgcniGiuZ6TZxW6VL.QDeF/e/0lSe');

--products
INSERT INTO product (name, description, price, quantity, image_url) VALUES
('Eco-Friendly Water Bottle', 'Durable and sustainable 20oz water bottle', 24.99, 75, 'https://example.com/bottle1.jpg'),
('Wireless Earbuds', 'High-quality sound with noise cancellation', 79.99, 32, 'https://example.com/earbuds1.jpg'),
('Yoga Mat', 'Non-slip, eco-friendly exercise mat', 39.99, 50, 'https://example.com/yogamat1.jpg'),
('Smart Watch', 'Fitness tracker with heart rate monitor', 129.99, 15, 'https://example.com/smartwatch1.jpg'),
('Portable Charger', '10000mAh power bank for mobile devices', 34.99, 88, 'https://example.com/charger1.jpg'),
('Bluetooth Speaker', 'Waterproof portable speaker', 59.99, 42, 'https://example.com/speaker1.jpg'),
('Stainless Steel Tumbler', 'Vacuum insulated 30oz tumbler', 29.99, 63, 'https://example.com/tumbler1.jpg'),
('Fitness Resistance Bands', 'Set of 5 resistance bands for workouts', 19.99, 95, 'https://example.com/bands1.jpg'),
('LED Desk Lamp', 'Adjustable brightness and color temperature', 44.99, 28, 'https://example.com/lamp1.jpg'),
('Backpack', 'Water-resistant laptop backpack', 69.99, 37, 'https://example.com/backpack1.jpg'),
('Wireless Mouse', 'Ergonomic design with silent clicks', 27.99, 81, 'https://example.com/mouse1.jpg'),
('Air Purifier', 'HEPA filter air cleaner for home', 89.99, 19, 'https://example.com/airpurifier1.jpg'),
('Coffee Maker', '12-cup programmable coffee machine', 49.99, 54, 'https://example.com/coffeemaker1.jpg'),
('Sunglasses', 'Polarized UV protection sunglasses', 54.99, 67, 'https://example.com/sunglasses1.jpg'),
('Smart Thermostat', 'WiFi-enabled programmable thermostat', 119.99, 23, 'https://example.com/thermostat1.jpg'),
('Wireless Keyboard', 'Slim, compact keyboard with numeric keypad', 39.99, 72, 'https://example.com/keyboard1.jpg'),
('Slow Cooker', '6-quart programmable slow cooker', 59.99, 36, 'https://example.com/slowcooker1.jpg'),
('Electric Toothbrush', 'Rechargeable sonic toothbrush', 79.99, 48, 'https://example.com/toothbrush1.jpg'),
('Noise-Cancelling Headphones', 'Over-ear headphones with active noise cancellation', 149.99, 21, 'https://example.com/headphones1.jpg'),
('Robot Vacuum', 'Smart navigation robotic vacuum cleaner', 199.99, 13, 'https://example.com/robotvacuum1.jpg'),
('Fitness Tracker', 'Slim activity tracker with sleep monitoring', 49.99, 59, 'https://example.com/fitnesstracker1.jpg'),
('Portable Blender', 'USB rechargeable personal blender', 34.99, 83, 'https://example.com/blender1.jpg'),
('Smart Light Bulbs', 'WiFi-enabled color changing LED bulbs', 29.99, 91, 'https://example.com/smartbulbs1.jpg'),
('Digital Food Scale', 'Precision kitchen scale with tare function', 19.99, 76, 'https://example.com/foodscale1.jpg'),
('Indoor Plant', 'Low-maintenance potted succulent', 24.99, 62, 'https://example.com/plant1.jpg'),
('Reusable Grocery Bags', 'Set of 5 foldable shopping bags', 14.99, 98, 'https://example.com/grocerybags1.jpg'),
('Wireless Charging Pad', 'Fast-charging Qi-compatible charging pad', 29.99, 70, 'https://example.com/chargingpad1.jpg'),
('Smart Door Lock', 'Keyless entry lock with smartphone control', 159.99, 17, 'https://example.com/doorlock1.jpg'),
('Portable Hammock', 'Lightweight camping hammock with straps', 39.99, 45, 'https://example.com/hammock1.jpg'),
('Essential Oil Diffuser', 'Ultrasonic aromatherapy diffuser', 32.99, 56, 'https://example.com/diffuser1.jpg'),
('Cordless Drill', '20V lithium-ion power drill set', 89.99, 31, 'https://example.com/drill1.jpg'),
('Cast Iron Skillet', '10-inch pre-seasoned cast iron pan', 29.99, 68, 'https://example.com/skillet1.jpg'),
('Bluetooth Car Adapter', 'Hands-free calling and music streaming adapter', 24.99, 85, 'https://example.com/caradapter1.jpg'),
('Weighted Blanket', '15 lbs therapeutic weighted blanket', 69.99, 39, 'https://example.com/blanket1.jpg'),
('Electric Kettle', 'Stainless steel variable temperature kettle', 44.99, 52, 'https://example.com/kettle1.jpg'),
('Foam Roller', 'High-density muscle roller for recovery', 19.99, 77, 'https://example.com/foamroller1.jpg'),
('Wireless Doorbell', 'Long-range waterproof doorbell kit', 34.99, 64, 'https://example.com/doorbell1.jpg'),
('Dash Cam', 'Full HD car dashboard camera', 79.99, 26, 'https://example.com/dashcam1.jpg'),
('French Press', '34 oz stainless steel coffee press', 27.99, 71, 'https://example.com/frenchpress1.jpg'),
('Hiking Boots', 'Waterproof trail hiking boots', 89.99, 34, 'https://example.com/hikingboots1.jpg'),
('Smart Plug', 'WiFi-enabled outlet with energy monitoring', 19.99, 93, 'https://example.com/smartplug1.jpg'),
('Infuser Water Bottle', '32 oz fruit infuser water bottle', 22.99, 80, 'https://example.com/infuserbottle1.jpg'),
('Telescoping Ladder', '12.5 ft aluminum extension ladder', 119.99, 11, 'https://example.com/ladder1.jpg'),
('Bike Lock', 'Heavy-duty U-lock with cable', 39.99, 58, 'https://example.com/bikelock1.jpg'),
('Indoor Security Camera', 'HD WiFi camera with two-way audio', 59.99, 40, 'https://example.com/securitycamera1.jpg'),
('Travel Pillow', 'Memory foam neck support pillow', 24.99, 86, 'https://example.com/travelpillow1.jpg'),
('Car Jump Starter', 'Portable battery booster and power bank', 79.99, 29, 'https://example.com/jumpstarter1.jpg'),
('Meal Prep Containers', 'Set of 10 BPA-free food storage containers', 29.99, 74, 'https://example.com/mealprep1.jpg'),
('Wireless Presenter', 'Laser pointer with slide control', 34.99, 60, 'https://example.com/presenter1.jpg'),
('Camping Stove', 'Portable propane camp stove', 49.99, 43, 'https://example.com/campstove1.jpg');
